apiVersion: v1
kind: Pod
metadata:
  name: ecc7r-sar-project-pod
spec:
  automountServiceAccountToken: false
  containers:
  - name: sar-debug
    image: ghcr.io/emcuttle/sar-damage:latest
    tty: true
    stdin: true
    workingDir: /data
    command: ["/bin/bash", "-c", "sleep infinity"]
    volumeMounts:
    - name: sar-pvc
      mountPath: /data
    resources:
      limits:
        memory: 10Gi
        cpu: "2"
      requests:
        memory: 4Gi
        cpu: "1"
  volumes:
  - name: sar-pvc
    persistentVolumeClaim:
      claimName: ecc7r-pv
  restartPolicy: Never
